name: "Deploy Service"
description: "Bump tag, build, and push a Docker image"

inputs:
  service:
    description: "Service name"
    required: true
  environment:
    description: "Deployment environment"
    required: true
  update_level:
    description: "Version bump level (major/minor/patch)"
    required: true
  docker_username:
    description: "Docker username"
    required: true
  docker_password:
    description: "Docker password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Bump tag
      id: bump
      uses: actions/github-script@v8
      with:
        github-token: ${{ github.token }}
        script: |
          const bumpTag = require('./.github/scripts/bump-tag.js');
          const result = await bumpTag({
            github,
            context,
            service: "${{ inputs.service }}",
            env: "${{ inputs.environment }}",
            updateLevel: "${{ inputs.update_level }}"
          });
          core.setOutput("latestTag", result.latestTag);
          core.setOutput("newTag", result.newTag);

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./services/${{ inputs.service }}
        push: true
        tags: ${{ inputs.docker_username }}/${{ inputs.service }}:${{ steps.bump.outputs.newTag }}