name: "Deploy Service"
description: "Bump tag, build, and push a Docker image"

inputs:
  service:
    description: "Service name"
    required: true
  environment:
    description: "Deployment environment"
    required: true
  update_level:
    description: "Version bump level (major/minor/patch)"
    required: true
  docker_username:
    description: "Docker username"
    required: true
  docker_password:
    description: "Docker password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Bump tag
      id: bump
      uses: actions/github-script@v8
      with:
        github-token: ${{ github.token }}
        script: |
          const {bumpTag} = require('./.github/scripts/bump-tag.js');
          const result = await bumpTag({
            github,
            context,
            service: "${{ inputs.service }}",
            env: "${{ inputs.environment }}",
            updateLevel: "${{ inputs.update_level }}"
          });
          core.setOutput("latestTag", result.latestTag);
          core.setOutput("newTag", result.newTag);

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ inputs.docker_username }}
    #     password: ${{ inputs.docker_password }}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: ./services/${{ inputs.service }}
    #     push: true
    #     tags: ${{ inputs.docker_username }}/${{ inputs.service }}:${{ steps.bump.outputs.newTag }}

    - name: Add summary
      run: |
        echo "### 🚀 Deployment Result" >> $GITHUB_STEP_SUMMARY
        echo "- **Service**: ${{ inputs.service }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Environment**: ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "- **New Tag**: \`${{ steps.bump.outputs.newTag }}\`" >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Notify Lark
      uses: herondlabs/action-lark-notify@main
      with:
        columnsPerRow: 2
        token: ${{ secrets.GITHUB_TOKEN }}
        cardItems: |
          **Repo**<br>[{{GITHUB_REPOSITORY}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}})
          **Channel**<br>{{CHANNEL}}
          **Actor**<br>{{GITHUB_ACTOR}} 
          **Branch**<br>[{{BRANCH}}]({{GITHUB_SERVER_URL || 'https://github.com'}}/{{GITHUB_REPOSITORY}}/tree/{{BRANCH}})
          **Build Logs**<br>[{{GITHUB_RUN_ID}}]({{GITHUB_JOB_URL}})
          **Release**<br>[{{GITHUB_TAG_VERSION}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/releases/tag/{{GITHUB_TAG_VERSION}})
      env:
        LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
        LARK_MESSAGE_TITLE: "Build Browser For Windows"
        LARK_MESSAGE_SUBTITLE: |
          Status: ${{ needs.build_windows.result }}
        LARK_MESSAGE_TEMPLATE: "${{ env.MSG_COLOR }}"
        RELEASE_TAG: ${{ inputs.tag }}
        CHANNEL: ${{ inputs.channel }}
        BRANCH: ${{ inputs.core_branch || env.GITHUB_REF_NAME }}      
